services:
  postgres:
    image: postgres:latest
    container_name: backend
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: backend
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
