export const AUTH_LABELS = {
  signIn: {
    title: "Bem-vindo de volta",
    description: "Entre com seu e-mail e senha para continuar.",
    emailLabel: "E-mail",
    emailPlaceholder: "voce@exemplo.com",
    passwordLabel: "Senha",
    passwordPlaceholder: "Sua senha",
    forgotPasswordLink: "Esqueci minha senha",
    submitButton: "Entrar",
    signUpText: "Ainda não tem conta?",
    signUpLink: "Criar conta",
  },
  signUp: {
    title: "Criar conta",
    description: "Preencha os dados para começar.",
    nameLabel: "Nome",
    namePlaceholder: "Seu nome completo",
    emailLabel: "E-mail",
    emailPlaceholder: "voce@exemplo.com",
    passwordLabel: "Senha",
    passwordPlaceholder: "Mínimo de 8 caracteres",
    confirmPasswordLabel: "Confirmar senha",
    confirmPasswordPlaceholder: "Repita a senha",
    submitButton: "Criar conta",
    signInText: "Já tem uma conta?",
    signInLink: "Entrar",
  },
  verifyEmailOtp: {
    title: "Confirme seu e-mail",
    description: "Enviamos um código de 6 dígitos para",
    codeLabel: "Código de verificação",
    codePlaceholder: "000000",
    submitButton: "Confirmar",
    resendButton: "Reenviar código",
    resendSuccess: "Enviamos um novo código para seu e-mail.",
    backToSignInLink: "Voltar para o login",
  },
  forgotPassword: {
    title: "Recuperar senha",
    description: "Enviaremos um código para você criar uma nova senha.",
    emailLabel: "E-mail",
    emailPlaceholder: "voce@exemplo.com",
    submitButton: "Enviar código",
    backToSignInLink: "Voltar para o login",
  },
  resetPassword: {
    title: "Nova senha",
    description: "Digite o código enviado para",
    codeLabel: "Código de verificação",
    codePlaceholder: "000000",
    passwordLabel: "Nova senha",
    passwordPlaceholder: "Mínimo de 8 caracteres",
    confirmPasswordLabel: "Confirmar nova senha",
    confirmPasswordPlaceholder: "Repita a nova senha",
    submitButton: "Redefinir senha",
    backToSignInLink: "Voltar para o login",
  },
  twoFactor: {
    title: "Verificação em duas etapas",
    description: "Digite o código do seu aplicativo autenticador.",
    codeLabel: "Código",
    codePlaceholder: "000000",
    submitButton: "Verificar",
    backToSignInLink: "Voltar para o login",
  },
} as const;
